version: '3.4'

services:
  retailbay.webadministration:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - ASPNETCORE_HTTPS_PORT=44371    
    ports:
      - "51468:80"
      - "44371:443"
    depends_on:
      - retailbay_postgres_server
    volumes:
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro

  retailbay.webshop:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - ASPNETCORE_HTTPS_PORT=44372  
    ports:
      - "51469:80"
      - "44372:443"
    depends_on:
      - retailbay_postgres_server
    volumes:
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro

  retailbay_postgres_server:
    image: postgres:alpine
    ports: 
      - "5432:5432"
    environment:
      POSTGRES_USER: "asp_test"
      POSTGRES_PASSWORD: "1234."
      POSTGRES_DB: "RetailBaySystem"
    volumes:      
      - pgdata:/var/lib/postgresql/data

  retailbay_elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch-oss:6.2.4
    container_name: retailbay_elasticsearch
    ports:
      - "9200:9200"
    volumes:
      - elasticsearch:/usr/share/elasticsearch/data

  retailbay_kibana:
    image: docker.elastic.co/kibana/kibana-oss:6.2.4
    container_name: retailbay_kibana
    ports:
      - "5601:5601"
    depends_on:
      - retailbay_elasticsearch
    environment:
      - ELASTICSEARCH_URL=http://retailbay_elasticsearch:9200

volumes:
  pgdata:
  elasticsearch: